Add history-clear command
dunst-project/dunst pull request #1131
Opened 2022-11-23 20:10 UTC by fapfaff

Added command to remove all notifications from history.

2022-11-23 22:46 UTC, fwsmit commented
Just curious, what do you use this for?

2022-11-23 22:49 UTC, fapfaff commented
For an eww widget displaying my notification history

2022-11-25 12:58 UTC, fapfaff commented
Do you have an idea why it doesn't build?
Shouldn't g_queue_clear_full() be included by glib.h?

Sorry for asking you my noob questions, but it's working locally without any problems and I couldn't find anything that helps me.

2022-11-27 17:15 UTC, fwsmit commented
I'm guessing the version of glib for these distro's is too old. You need at least version 2.6 to get this function. I've ran the archlinux build again and it works. This seems to confirm my suspicion. vTake a look at https://docs.gtk.org/glib/struct.Queue.html for the version requirements of different functions.

You can work around this by using other queue functions in glib.

2022-11-27 20:41 UTC, fapfaff commented
Thanks, I have replaced it. Should work now.

2022-11-27 22:32 UTC, fwsmit requested changes

2022-11-27 22:32 UTC, fwsmit commented on src/queues.c
>          if (g_queue_is_empty(history))
This is unnecesary

2022-11-27 22:32 UTC, fwsmit commented on src/queues.c
> +        }
You can actually use the source of glib to copy the function here. See https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/gqueue.c#L166

```
g_queue_foreach (queue, (GFunc) free_func, NULL);
g_queue_clear (queue);
```

2022-12-13 16:04 UTC, fwsmit commented
LGTM, thanks!

2022-12-13 16:05 UTC, merged